name: Build Zephyr

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install west
        run: pip install west

      - name: Init NCS
        run: |
          west init -m https://github.com/nrfconnect/sdk-nrf --mr v2.7.0 ncs
          cd ncs
          west update

      - name: Build
        run: |
          cd ncs
          export ZEPHYR_BASE=$(pwd)/zephyr
          west build -s ../ -b seeed_xiao_nrf52840 -d build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: firmware
          path: ncs/build/zephyr/*.hex
